define({
	SC_OK:'确定',
	SC_CANCEL:'Cancel',
	SC_BALANCE:'余额',
	SC_SIGN_IN:'登录 ',
	SC_SIGN_UP:'注册',
	SC_LOGIN:'登录',
	SC_MOBILE_NUMBER:'号码',
	SC_PASSWORD:'密码',
	SC_REMEBER:'记住登录',
	SC_FORGET_PWD:'忘记密码',
	SC_LOGIN_WITH_CODE:'验证码登录',
	SC_DONNOT_HAVE_ACCOUNT:'没有账号',
	SC_REPEAT_PWD:'确认密码',
	SC_VER_CODE:'验证码',
	SC_GET :'获取',
	SC_REGISTRATION:'注册',
	SC_HAVE_ACCOUNT:'已有账号 ',
	SC_ENTER_NBR_4_FORGET:'输入你的号码来重置密码',
	SC_SEND_MSG_4_FORGET:'新密码将以短信方式发送到手机',
	SC_BACK_TO_LOGIN:'返回登录',
	SC_SUBMIT:'提交',
	SC_LOGOUT: '退出',
	SC_LOGOUT_CONFIRM :'确定要退出 ?',
	SC_POSTPAID :'后付费',
	SC_PREPAID : '预付费',
	
	SC_WELCOME:'欢迎回来!',
	SC_SUBSCRIPTION :'套餐',
	SC_YOUR_NUMBER:'号码',
	SC_ACTIVE_SINCE:'激活时间',
	SC_PAID_TYPE:'付费类型',
	SC_DATA_NOT_FOUND:'未找到数据',
	
	SC_ACCOUNT_NO:'账号',
	SC_CONSUME_BALANCE:'消费额',
	SC_REMAIN_BALANCE:'余额',
	SC_FROM:'从',
	SC_TO:'到',
	SC_DUE:'应缴',
	SC_TOTAL_USAGE:'总计',
	SC_LAST_TOP_UP:'上次充值',
	SC_MORE : '更多..',
	SC_BLOCK_REASON:"停机原因:",
	SC_BLOCK_REASON_1 :"客户申请停机",
	SC_BLOCK_REASON_2 :"强制停机",
	SC_BLOCK_REASON_3 :"欠费停机",
	SC_BLOCK_REASON_4 :"高额使用费停机",
	SC_BLOCK_REASON_5 :"申请预拆机",
	SC_BLOCK_REASON_6 :"余额失效",
	SC_BLOCK_REASON_7 :"充值黑名单",
	SC_BLOCK_REASON_8 :"卡挂失",
	SC_BLOCK_REASON_9 :"呼叫黑名单",
	SC_BLOCK_REASON_10 :"客户黑名单",
	SC_BLOCK_REASON_11 :"预转后",
	SC_BLOCK_REASON_12 :"Reserved 1",
	SC_BLOCK_REASON_13 :"Reserved 2",
	SC_BLOCK_REASON_14 :"Reserved 3",
	
	SC_DETAIL:'详情',
	SC_POINTS:'积分',
	SC_CONTACT_US:'联系我们',
	SC_REAL_TIME_USAGE:'实时余额',
	SC_USAGE_TOTAL:'总计使用',
	SC_MONTHLY_CHARGE:'月租费',
	SC_ONETIME_CHARGE:'一次性费',
	SC_TOTAL:'总计',
	SC_USAGE_DETAIL:'使用详情',
	
	SC_CHANGE_PWD:'修改密码',
	SC_CUSTOMER_NAME:'客户名',
	SC_OLD_PWD :'原密码',
	SC_CONFIRM_PWD:'确认密码',
	SC_SECURITY_LEVEL:'密码强度',
	SC_LOWER:'较低',
	SC_LOW:'低',
	SC_MEIDUM:'中等',
	SC_HIGH:'高',
	SC_HIGHER:'较高',
	SC_CHANGE_PWD_HINT1:'修改密码流程描述, 密码修改成功后会发送短信.',
	SC_CHANGE_PWD_HINT2:'密码必须是6-12位的字符',
	SC_MYPROFILE :'我的资料',
	SC_CREATED_DATE :'开户时间',
	SC_DOC_TYPE:'证件类型',
	SC_DOC_NUMBER:'证件号码',
	SC_GENDER:'性别',
	SC_BIRTHDAY:'生日',
	SC_EMAIL_ADDRESS:'Email',
	SC_ADDRESS:'地址',
	SC_CONTACT_NUMBER:'联系号码',
	SC_OCCUPATION:'职业',
	SC_EDIT:'修改',
	SC_CUSTOMER_TYPE :'客户类型',
	SC_OPERATOR_TYPE :'操作员类型',
	SC_EXCEED_SIX_MONTH:'只能查6个月内的记录',
	SC_CONTACT_CONTENT:'接触内容',
	
	SC_LOGIN_HISTORY:'登录历史',
	SC_HISTORY_HINT1:'最近6个月的历史',
	SC_HISTORY_HINT2:'其他查询,请联系管理员',
	SC_LOGIN_IP:'登录IP',
	SC_LOGIN_DATE:'登录时间',
	SC_SUBSCRIBER_NUMBER:'订户号',
	
	SC_TAX_INCLUDE:'包含5%的税',
	SC_DOMESTIC_CALL:'国内长途',
	SC_OVERSEA_CALL:'国际长途',
	SC_SMS_FEE:'短信费',
	SC_GRRS_FEE:'流量费',
	SC_CRBT_FEE:'CRBT Fee',
	SC_M118_FEE:'M188 Fee',
	SC_CALL_CENTER_FEE:'呼叫中心费',
	SC_COMMERCIAL_TAX:'商业税',
	SC_CURRENT_TOTAL:'当月合计',
	SC_ADJUSTMENT:'调账',
	SC_OPEN_BALANCE:'Opening Balance',
	SC_CLOSE_BALANCE:'Closing Balance',
	SC_BILL_MONTH:'账单月份',
	SC_BILL_NO:'账单号.',
	SC_PAYMENT_PERIOD:'付费时段',
	SC_BILL_AMOUNT:'总计',
	SC_ADVANCE_PAYMENT:'高级明细',
	
	SC_CONTACT_HISTORY:'接触历史',
	SC_CONTACT_DATE:'接触时间',
	SC_CONTACT_CHANNEL:'接触渠道',
	SC_MPT_STORE:'MPT Store',
	SC_CALL_CENTER:'Call Center',
	SC_SELFCARE:'SelfCare',
	
	SC_DATE :'时间',
	SC_CHANNEL:'渠道',
	SC_EVENT:'事件',
	SC_OPERATOR:'操作员',
	
	SC_ORDER_INFO:'订单确认',
	SC_OFFER:'销售品',
	SC_CHARGE:'费用',
	SC_YOUR_BALANCE:'你的余额',
	SC_EFFECTIVE_TYPE:'生效类型',
	SC_FEATURE:'主题',
	SC_ADD_ON_OFFER:'依赖产品',
	SC_PRICE_PLAN:'资费计划',
	SC_VAS_OFFER:'VAS Offer',
	SC_MY_PAKCAGE:'已订购的包',
	SC_OPTIONAL_PKG_OFFER:'可选包订购',
	SC_MY_VAS:'VAS订购',
	SC_OPTIONAL_VAS:'可选VAS订购',
	SC_HINT_BAL_NOT_ENOUGH:'余额不足, 请先充值.',
	SC_HINT_SUCCESS_SUBMIT_ORDER:'提交订单成功, 订单在后台流转, 请稍后查看',
	SC_MONTHLY_RENTAL:'月租',
	SC_FREE:'Free',
	SC_KYATS:'Kyats',
	SC_BUY:'订购',
	SC_ENABLE:'可用',
	SC_CONFIRM_CANCEL_PACKAGE:'确定要取消订购?',
	SC_DISABLE:'取消',
	SC_CONFIRM_DISABLE_VAS:'确定要取消?',
	SC_FRIDNDS_AND_FAMILY_NBR:'亲情号码',
	SC_FELLOW_NBR_COMMENTS1:'亲情号码可以让客户去添加普通号码进入群组,来享受特殊 优惠.',
	SC_FELLOW_NBR_COMMENTS2:'你可以管理亲情号码, 包括添加和删除成员',
	SC_MY_FRIDNDS_AND_FAMILY_NBR:'我的亲情号码',
	SC_ADD_FRIDNDS_AND_FAMILY_NBR:'添加亲情号码',
	SC_NUMBER:'号码',
	SC_PLEASE_ENTER_FELLOW_NBR:'请输入主号',
	SC_EFF_DATE:'生效时间',
	SC_EXP_DATE:'失效时间',
	SC_ADD:'添加',
	SC_CONFIRM_DELETE_FELLOW_NUMBER:'确认取消这个号码?',
	SC_SIM_LOST_RESTORE:'SIM 挂失',
	SC_SIM_LOST_RESTORE_COMMENTS1:'当你丢失SIM卡,你可以申临时请暂停服务并且保持持有该号码',
	SC_SIM_LOST_RESTORE_COMMENTS2:'当你补办卡, 你可以重新激活你的服务',
	SC_ICCID:'ICCID',
	SC_PUK1:'PUK1',
	SC_PUK2:'PUK2',
	SC_STATUS:'状态',
	SC_STATUS_DATE:'状态时间',
	SC_SIM_CARD_LOST:'SIM卡 挂失',
	SC_SIM_CARD_RESTORE:'SIM 补卡',
	SC_CONFIRM_LOST_SIM_CARD:'确定挂失?',
	SC_CONFIRM_RESTORE_SIM_CARD:'确定补卡 ?',
	SC_TOP_UP:'充值',
	SC_HISTORY:'历史',
	SC_TOP_UP_COMMENTS:'使用PIN卡来充值.',
	SC_MY_BALANCE:'账户余额',
	SC_VOUCHER_PIN:'充值卡 PIN',
	SC_HINT_ENTER_DIGIT_RECHARGE_PWD:'请输入19位充值密码',
	SC_RECHARGE:'充值',
	SC_TOP_UP_HIS_COMMENTS1:'其他查询,请联系管理员.',
	SC_TOP_UP_HIS_COMMENTS2:'充值记录只作为参考,不作为凭证',
	SC_TOP_UP_HIS_COMMENTS3:'充值记录展示过去6月',
	SC_NEARLY_THREE_MONTH:'最近3个月',
	SC_NEARLY_SIX_MONTH:'最近6个月',
	SC_CUST_TIME:'自定义',
	SC_CUSTOMER_NAME:'客户名称',
	SC_TOTAL_AMOUNT:'总数',
	SC_TOTAL_RECORD:'总记录',
	SC_PAYMENT_DATE:'充值时间',
	SC_PAYMENT_METHOD:'充值方式',
	SC_SUBMIT_AMOUNT:'提交数量',
	SC_BALANCE_EXPIRE_DATE:'余额失效时间',
	SC_CREDIT:'信用',
	SC_HINT_RECHARGE_SUCCESS:'充值成功',
	SC_RECORD:'记录',
	SC_TRANSFER:'转账',
	SC_TRANSFER_BAL_COMMENTS1:'转账从MPT号码转入另一个MPT号码',
	SC_TRANSFER_BAL_COMMENTS2:' 转账金额不能超过账户余额或者信用度。',
	SC_TRANSFER_BAL_COMMENTS3:'服务费: 转账额的x%',
	SC_RECEIVER_NUMBER:'转入号码',
	SC_TRANSFER_AMOUNT:'转出号码',
	SC_SERVICE_CHARGE:'服务费',
	SC_TRANSFER_HIS_COMMENTS1:'其他查询,请联系管理员',
	SC_TRANSFER_HIS_COMMENTS2:'查询出来的转账记录只作为参考,不作为凭证.',
	SC_TRANSFER_HIS_COMMENTS3:'转账记录保留6个月',
	SC_OTHER:'其他',
	SC_AMOUNT_BETWEEN:'( 请输入 {0} Kyats and {1} Kyats ) ',
	SC_TRANSFER_DATE:'转账时间',
	SC_HINT_SUCCESS_TRANSFER:'转账成功.',
	SC_MY_ORDERS:'我的商品',
	SC_MY_ORDERS_COMMENTS1:'最近6个月历史数据',
	SC_MY_ORDERS_COMMENTS2:'其他查询，请联系客户中心',
	SC_MY_OFFER_NAME:'商品名称',
	SC_MY_ACTIVE_DATE:'激活日期',
	SC_MY_TERMINATION:'拆机',
	SC_MY_TWO_WAY_BLOCK:'停机',
	
	
	SC_TROUBLE_TICKET:'故障单',
	SC_CREATE:'创建',
	SC_CREATE_DESCRIPTION:'描述',
	SC_TYPE:'类型',
	SC_TITLE:'主题',
	SC_COMMENTS:'内容',
	SC_CONTACT_NUMBER:'联系电话',
	SC_SUCCESS_TO_SEND_EMAIL:'发送邮件成功',
	
	SC_CALL_HISOTY_TITLE:'历史记录',
	SC_DESCRIPTION_MSG_1:'近六个月',
	SC_DESCRIPTION_MSG_2:'如有疑问请联系客服.',
	SC_DESCRIPTION_MSG_3:'这些记录进攻参考，不做任何凭据.',
	SC_OTHER_TIME:'其他时间',
	SC_VOICK:'Voice',
	SC_DATA:'DATA',
	SC_SMS:'SMS',
	SC_VAS_PROD:'VAS 产品',
	SC_CUST_NAME:'客户名称',
	SC_MOBILE_NO:'手机号码',
	SC_PRINT:'打印',
	SC_DOWNLOAD:'下载',
	SC_BILLING_CYCLE:'账单周期',
	SC_TOTAL_DATA:'所有数据',
	SC_MY_BILLING_TITLE:'我的账单',
	
	SC_LOAN_BALANCE:'贷款',
	SC_LOAN_TAB:'贷款',
	SC_HISTORY_TAB:'贷款历史',
	SC_LOAN_MSG_1:'当你的主账本余额小于200 Kyats 时，你可以从 MPT借贷800 Kyats。',
	SC_LOAN_MSG_2:'800 Kyats 会放在你的贷款账本中，有效期为30天。',
	SC_LOAN_MSG_3:'手续费会加到你的贷款金额800中，意思是，你付款时需要付830 Kyats。',
	SC_MOBILE_NUMBER:'手机号码',
	SC_MY_BALANCE:'我的余额',
	SC_LOAN_AMOUNT:'贷款金额',
	SC_SERVICE_CHARGE:'手续费',
	SC_SUBMIT_LOAN:'提交贷款',
	SC_HISTORY_MSG_1:'如有疑问，可联系客服，',
	SC_HISTORY_MSG_2:'贷款记录只提供参考，不作为任何凭证。',
	SC_HISTORY_MSG_3:'这里最多提供近6个月的记录',
	SC_NEARLY_THREE_MONTHS:'最近三个月',
	SC_NEARLY_SIX_MONTHS:'最近6个月',
	SC_CUST_SELECT_TIME:'时间域查询',
	SC_LOAN_DATE:'贷款日期',
	SC_LOAN_CONFIRM_MSG:'这个手续费是53 Kyats，你确定订购吗？',
	SC_SMS:'SMS',
	SC_Oversea_Call:'Oversea Call',
	SC_Service_Charges:'Service Charges',
	SC_Domestic_Call:'Domestic Call',
	SC_Monthly_Rental:'Monthly Rental',
	SC_GRPS:'GRPS',
	SC_CRBT:'CRBT',
	SC_M118:'M118',
	SC_CALL_CENTER:'CALL CENTER',
	SC_Commercial_Tax:'Commercial Tax',
	SC_DATA_PACKAGE:'Data Package',
	SC_CUST_NRC_SIZE:'The file size is less than 10M.',
	SC_CUST_NRC_TYPE:'The format of the picture must be JPG/JPEG.PNG.',
	SC_CUST_NRC_FRONT_UPLOAD:'Upload your NRC front-side image',
	SC_CUST_NRC_BACK_UPLOAD:'Upload your NRC back-side image',
	SC_CUST_NRC_FRONT_SIDE:'NRC front-side',
	SC_CUST_NRC_BACK_SIDE:'NRC back-side',
	SC_CUST_NRC_SELECT:'Please select NRC.',
	SC_CUST_NRC_SELECT_FRONT:'Please select front-side NRC.',
	SC_CUST_NRC_SELECT_BACK:'Please select back-side NRC.',
	SC_CUST_NRC_FILE_EMPTY:'Upload file can not be empty.',
	SC_CUST_NRC_EXCEED_MAX:'Upload File Exceed Max. 10M',
	SC_CUST_NRC_FAIL:'Upload fail.',
	SC_CUST_NRC_IS_NULL:'Important Notification.<br/>Thank you for using MPT mobile service.<br/>Due to the guidance of government.<br/>All Mobile user needed to register their \'NRC\'.<br/>So, Please enter in \'My information>Customer Profile\',<br/>then you can upload a photo of NRC, thank you.',
	SC_CUST_NRC_IMG_FORMAT_ERROR:'The file should be end with jpg,jpeg or png.',
	SC_PASSWORD_CHAR_NUMBER_UPPER : '密码需包含数字、大小写字母和特殊字符。',
	SC_ACCOUNT_LOCKED_HALFHOUR : '账户被锁定，30分钟后请重试。',
	SC_PASSWORD_NOT_CORRECT : '输入的密码不正确。',
	SC_REPEAT_PASSWORD_NOT_MATCH : '重复输入的密码不一致。',
	SC_CUST_NRC_SELECT_BACK : 'Please wait for the NRC back-side image upload complete.',
	SC_CUST_NAME_TOO_LANG: '输入用户名太长了，请控制在60个字符之内',
	SC_MENU_INFO:'Here is the menu.',
	SC_EDIT_CERT_NBR_ERROR:'Failed to edit customer information, because the cert number is over range.'
});