package com.ztesoft.zsmart.bss.selfcare.model;

/**
 * <p>Title:ZSMART </p>
 *
 * <p>Description: CertTypeDto </p>
 *
 * <p>Copyright: Copyright (c) 2008</p>
 *
 * <p>Company:ztesoft </p>
 *
 * <p>Created Date:2011-12-31 9:34:26 </p>
 *
 * @author:   Auto Generated by CodeSmith 3.0 
 * @version R11
 */

import java.io.Serializable;

import com.ztesoft.zsmart.core.exception.BaseAppException;
import com.ztesoft.zsmart.core.jdbc.AbstractDto;
import com.ztesoft.zsmart.core.jdbc.Validater;

/**
 * [描述] <br>
 * 
 * @author [作者名]<br>
 * @version 1.0<br>
 * @taskId <br>
 * @CreateDate 2013-9-22 <br>
 * @since V7.0<br>
 * @see com.ztesoft.zsmart.bss.common.model <br>
 */
public class CertTypeDto extends AbstractDto implements Serializable, Validater {
    /**
     * serialVersionUID <br>
     */
    private static final long serialVersionUID = 7386962815475447097L;

    /** 证件类型标识 */
    public Long certTypeId;

    /** 客户类型 */
    public String custType;

    /** 名称 */
    public String certTypeName;

    /** Code */
    public String certTypeCode;

    /** 说明 */
    public String comments;

    /** 格式，正则表达式 */
    public String nbrMask;

    /** 号码最大长度 */
    public Long maxNbrLength;

    /** 号码最小长度 */
    public Long minNbrLength;

    /** SP_ID */
    public Long spId;

    /** nbrExample */
    public String nbrExample;

    /**
     * CertTypeDto
     */
    public CertTypeDto() {
    }

    /**
     * 校验函数
     * 
     * @param
     * @throws BaseAppException 应用异常
     */
    public void validate() throws BaseAppException {
        throw new java.lang.UnsupportedOperationException();
    }

    /**
     * 构造函数
     * 
     * @param certTypeId Long;
     * @param custType String;
     * @param certTypeName String;
     * @param certTypeCode String;
     * @param comments 备注;
     * @param nbrMask String;
     * @param maxNbrLength Long;
     * @param minNbrLength Long;
     * @param spId SP_ID;
     * @param nbrExample String;
     */
    public CertTypeDto(Long certTypeId, String custType, String certTypeName, String certTypeCode, String comments,
        String nbrMask, Long maxNbrLength, Long minNbrLength, Long spId, String nbrExample) {
        this.certTypeId = certTypeId;
        this.custType = custType;
        this.certTypeName = certTypeName;
        this.certTypeCode = certTypeCode;
        this.comments = comments;
        this.nbrMask = nbrMask;
        this.maxNbrLength = maxNbrLength;
        this.minNbrLength = minNbrLength;
        this.spId = spId;
        this.nbrExample = nbrExample;
    }

    public Long getCertTypeId() {
        return certTypeId;
    }

    public void setCertTypeId(Long certTypeId) {
        this.certTypeId = certTypeId;
    }

    public String getCustType() {
        return custType;
    }

    public void setCustType(String custType) {
        this.custType = custType;
    }

    public String getCertTypeName() {
        return certTypeName;
    }

    public void setCertTypeName(String certTypeName) {
        this.certTypeName = certTypeName;
    }

    public String getCertTypeCode() {
        return certTypeCode;
    }

    public void setCertTypeCode(String certTypeCode) {
        this.certTypeCode = certTypeCode;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getNbrMask() {
        return nbrMask;
    }

    public void setNbrMask(String nbrMask) {
        this.nbrMask = nbrMask;
    }

    public Long getMaxNbrLength() {
        return maxNbrLength;
    }

    public void setMaxNbrLength(Long maxNbrLength) {
        this.maxNbrLength = maxNbrLength;
    }

    public Long getMinNbrLength() {
        return minNbrLength;
    }

    public void setMinNbrLength(Long minNbrLength) {
        this.minNbrLength = minNbrLength;
    }

    public Long getSpId() {
        return spId;
    }

    public void setSpId(Long spId) {
        this.spId = spId;
    }

    public String getNbrExample() {
        return nbrExample;
    }

    public void setNbrExample(String nbrExample) {
        this.nbrExample = nbrExample;
    }
}
